formatter: "markdown"

recursive:
  enabled: true
  path: examples

output:
  file: "README_2.md"
  mode: replace

settings:
  color: false
  description: "true"
  hide-empty: true
  read-comments: true
  sensitive: true
  lockfile: true

sort:
  enabled: true
  by: required